DATAS	SEGMENT
BUFFER		DB			0,1,2,3,4,5	,6,7
DATA1		DW		6565H,6565H
DATA2		DW		2323H,2323H
SUM			DW		2  DUP(0)
DATAS	ENDS

CODES	SEGMENT
ASSUME		DS:DATAS,	CS:CODES
START: 	MOV		AX,	DATAS
        	MOV		DS,	AX			;
FIRST:		LEA		SI,		DATA1
        	LEA		BX,	DATA2
			MOV		DI,		OFFSET	SUM
SECOND:	MOV		AX,	[SI]
ADD		AX,	[BX]
MOV		[DI],	AX
THIRD:	MOV		AX,	[SI+2]
ADC		AX,	[BX +2]
MOV		[DI +2],	AX
        	MOV		AX，	4C00H		;
		  	INT		21H
CODES	ENDS
END	START
